services:
  web:
    build: ./backend
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    #    volumes:
    #      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nuxt-app:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_ENV_API_URL=http://web:8000/api
    depends_on:
      - web
#      volumes:
#        - ./frontend/my-nuxt-app:/app


volumes:
  postgres_data:
