# Generated by Django 3.2.25 on 2025-02-25 05:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('waypoint_type', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], max_length=10)),
                ('transport_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='transport_orders.transportorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
